import { StyleSheet } from "@react-pdf/renderer";

export const dayNames = [
  "Minggu",
  "Senin",
  "Selasa",
  "Rabu",
  "Kamis",
  "Jumat",
  "Sabtu",
];

export const monthNames = [
  "Januari",
  "Februari",
  "Maret",
  "April",
  "Mei",
  "Juni",
  "Juli",
  "Agustus",
  "September",
  "Oktober",
  "November",
  "Desember",
];

export const styles = StyleSheet.create({
  page: {
    flexDirection: "column",
    backgroundColor: "#FFFFFF",
    padding: 40,
    fontSize: 9,
    fontFamily: "Helvetica",
    lineHeight: 1.4,
  },
  header: {
    marginBottom: 25,
    borderBottom: 3,
    borderBottomColor: "#2563eb",
    paddingBottom: 15,
    alignItems: "center",
  },
  headerContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  logo: {
    width: 60,
    height: 60,
    marginRight: 15,
  },
  titleContainer: {
    flex: 1,
    alignItems: "center",
  },
  title: {
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 8,
    color: "#1e40af",
    letterSpacing: 0.5,
  },
  subtitle: {
    fontSize: 10,
    textAlign: "center",
    marginBottom: 3,
    color: "#374151",
  },
  reportTitle: {
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 25,
    textDecoration: "underline",
    color: "#1e40af",
    letterSpacing: 1,
  },
  table: {
    display: "flex",
    width: "auto",
    borderStyle: "solid",
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 4,
    marginBottom: 25,
    overflow: "hidden",
  },
  tableHeaderRow: {
    flexDirection: "row",
    backgroundColor: "#3b82f6",
    borderBottomWidth: 2,
    borderBottomColor: "#1e40af",
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
    minHeight: 35,
  },
  tableRowEven: {
    flexDirection: "row",
    backgroundColor: "#f8fafc",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
    minHeight: 35,
  },
  tableColHeader: {
    borderRightWidth: 1,
    borderRightColor: "#1e40af",
    padding: 8,
    fontWeight: "bold",
    textAlign: "center",
    color: "#ffffff",
    fontSize: 9,
    justifyContent: "center",
    alignItems: "center",
  },
  tableCol: {
    borderRightWidth: 1,
    borderRightColor: "#e5e7eb",
    padding: 6,
    textAlign: "center",
    fontSize: 8,
    justifyContent: "center",
    alignItems: "center",
    flexWrap: "wrap",
  },
  noCol: {
    width: "6%",
    minWidth: 25,
  },
  nameCol: {
    width: "22%",
    textAlign: "left",
    paddingLeft: 8,
  },
  addressCol: {
    width: "15%",
  },
  typeCol: {
    width: "13%",
  },
  dateCol: {
    width: "17%",
    fontSize: 7,
  },
  verificationCol: {
    width: "10%",
  },
  summary: {
    marginBottom: 25,
    padding: 15,
    backgroundColor: "#f1f5f9",
    borderRadius: 8,
    borderLeft: 4,
    borderLeftColor: "#3b82f6",
  },
  summaryTitle: {
    fontSize: 12,
    fontWeight: "bold",
    marginBottom: 8,
    color: "#1e40af",
  },
  summaryText: {
    fontSize: 10,
    marginBottom: 4,
    color: "#374151",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  summaryLabel: {
    fontWeight: "normal",
  },
  summaryValue: {
    fontWeight: "bold",
    color: "#1e40af",
  },
  footer: {
    marginTop: 40,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  footerLeft: {
    flex: 1,
  },
  footerRight: {
    alignItems: "center",
    flex: 1,
  },
  dateText: {
    fontSize: 10,
    marginBottom: 5,
    color: "#374151",
  },
  signatureTitle: {
    fontSize: 11,
    fontWeight: "bold",
    marginBottom: 40,
    color: "#1e40af",
  },
  signature: {
    alignItems: "center",
  },
  signatureName: {
    fontWeight: "bold",
    textDecoration: "underline",
    fontSize: 11,
    marginBottom: 3,
  },
  signatureNip: {
    fontSize: 9,
    color: "#6b7280",
  },
  pageNumber: {
    position: "absolute",
    fontSize: 9,
    bottom: 20,
    left: 0,
    right: 0,
    textAlign: "center",
    color: "#6b7280",
  },
  statusVerified: {
    color: "#059669",
    fontWeight: "bold",
  },
  statusNotVerified: {
    color: "#dc2626",
    fontWeight: "bold",
  },
});
