import "./globals.css";
import Navbar from "../components/Navbar/index";
import Footer from "../components/Footer";

export const metadata = {
  title: "Geopark Merangin Jambi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
